spring:
  profiles:
    active: local

  # JPA 공통 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Mail 공통 (프로토콜 고정)
  mail:
    protocol: smtp

# 공통 JWT 설정
jwt:
  expiration-ms: 3600000        # 1시간 (Access Token)
